### ISSUE TITLE
.env file is not used

### ISSUE THREAD

**Issue by lagivan** [alex000kim/slack-gpt-bot#1]
After following the installation steps, I'm getting the errors when running `python slack_gpt_bot.py`:

```
Traceback (most recent call last):
  File "/Users/myuser/Documents/GitRepositories/os/slack-gpt-bot/slack_gpt_bot.py", line 10, in <module>
    app = App(token=SLACK_BOT_TOKEN)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/slack_bolt/app/app.py", line 345, in __init__
    self._init_middleware_list(
  File "/opt/homebrew/lib/python3.11/site-packages/slack_bolt/app/app.py", line 397, in _init_middleware_list
    raise BoltError(error_token_required())
slack_bolt.error.BoltError: Either an env variable `SLACK_BOT_TOKEN` or `token` argument in the constructor is required.
```

When I run with real env variables, it works fine:
```
SLACK_BOT_TOKEN=... \
SLACK_APP_TOKEN=... \
OPENAI_API_KEY=... \
python slack_gpt_bot.py 
```

Is something like `load_dotenv()` missing in the code? I could not make it work myself so asking for support.

**Comment by good-lly** [comment]
you can try this -> https://github.com/alex000kim/slack-gpt-bot/pull/3

works for me

**Comment by lagivan** [comment]
@good-lly thanks, works for me as well

**Comment by alex000kim** [comment]
https://github.com/alex000kim/slack-gpt-bot/pull/3 merged
